<?php
/**
 * Avatar Module
 *
 * The Avatar module allows uploading of individual Avatars.
 * It is based on EnvoAvatar from A.T.Web, http://www.atw.it
 *
 * @package      Avatar
 * @version      $Id$
 * @author       Joerg Napp, Frank Schummertz
 * @link         http://lottasophie.sf.net
 * @copyright    Copyright (C) 2004
 * @license      http://www.gnu.org/copyleft/gpl.html GNU General Public License
 */

/**
 * the main administration function
 *
 * This function is the default function, and is called whenever the
 * module is called without defining arguments.
 * As such it can be used for a number of things, but most commonly
 * it either just shows the module menu and returns or calls whatever
 * the module designer feels should be the default function (often this
 * is the view() function)
 *
 * @author       Jörg Napp, Frank Schummertz
 * @return       output       The main module admin page.
 */
function Avatar_admin_main()
{
    if (!SecurityUtil::checkPermission('Avatar::', '::', ACCESS_ADMIN)) {
        return LogUtil::registerPermissionError('index.php');
    }
    
    $pnRender = new pnRender('Avatar');
    return $pnRender->fetch('Avatar_admin_main.htm');
} 

/**
 * avatar maintenance
 *
 *
 * @author       Frank Schummertz
 * @return       output       The maintenance admin page.
 */
function Avatar_admin_maintain()
{
    if (!SecurityUtil::checkPermission('Avatar::', '::', ACCESS_ADMIN)) {
        return LogUtil::registerPermissionError('index.php');
    }
    
    $pnRender = new pnRender('Avatar');
    return $pnRender->fetch('Avatar_admin_maintain.htm');
} 
 
/**
 * modify the configuration
 *
 * @author       Jörg Napp, Frank Schummertz
 * @return       output       The modify config page.
 */
function Avatar_admin_modifyconfig()
{
    if (!SecurityUtil::checkPermission('Avatar::', '::', ACCESS_ADMIN)) {
        return LogUtil::registerPermissionError('index.php');
    }

    Loader::requireOnce('modules/Avatar/pnincludes/Avatar_admin_modifyconfighandler.class.php');

    // Create output object
    $pnf = FormUtil::newpnForm('Avatar');

    // Return the output that has been generated by this function
    return $pnf->pnFormExecute('Avatar_admin_modifyconfig.htm', new Avatar_admin_modifyconfighandler());
}

?>