<?php
/**
 * Avatar Module
 *
 * The Avatar module allows uploading of individual Avatars.
 * It is based on EnvoAvatar from A.T.Web, http://www.atw.it
 *
 * @package      Avatar
 * @version      $Id$
 * @author       Joerg Napp
 * @link         http://lottasophie.sf.net
 * @copyright    Copyright (C) 2004
 * @license      http://www.gnu.org/copyleft/gpl.html GNU General Public License
 */


/**
 * the main administration function
 *
 * This function is the default function, and is called whenever the
 * module is called without defining arguments.
 * As such it can be used for a number of things, but most commonly
 * it either just shows the module menu and returns or calls whatever
 * the module designer feels should be the default function (often this
 * is the view() function)
 *
 * @author       The PostNuke Development Team
 * @return       output       The main module admin page.
 */
function Avatar_admin_main()
{
    if (!SecurityUtil::checkPermission('Avatar::', '::', ACCESS_ADD)) {
        return LogUtil::registerPermissionError('index.php');
    }

    // get all groups
    $orig_groups = pnModAPIFunc('Groups', 'user', 'getall');
    foreach($orig_groups as $orig_group) {
        $groups[$orig_group['gid']] = $orig_group['name']; 
    }
    $groups[0] = _AVATAR_ADM_GROUPS_ALL;
    ksort($groups);


    $pnRender = new pnRender('Avatar');

    // We need the pnsecgenauthkey plugin, so we must not cache here.
    $pnRender->caching = false;
    $pnRender->add_core_data();

    $pnRender->assign('groups',             $groups);
    $pnRender->assign('warn_avatardir',     !is_writable(pnModGetVar('Avatar', 'avatardir')));
    $pnRender->assign('pnphpbb_installed',   pnModAvailable('pnphpbb'));
    $pnRender->assign('warn_forumdir',      !is_writable(pnModGetVar('Avatar', 'forumdir')));

    // Return the output that has been generated by this function
    return $pnRender->fetch('Avatar_admin_main.htm');
}

/**
 * Avatar_admin_save()
 *
 * Save the settings made.
 *
 * @return
 **/
function Avatar_admin_save()
{
    if (!SecurityUtil::checkPermission('Avatar::', '::', ACCESS_ADD)) {
        return LogUtil::registerPermissionError('index.php');
    }

    if (!SecurityUtil::confirmAuthKey()) {
        return LogUtil::registerAuthidError('index.php');
    }

    
    $avatardir          = FormUtil::getPAssedValue('avatardir', 'images/avatar', 'POST');
    $forumdir           = FormUtil::getPAssedValue('forumdir', '', 'POST');
    $maxsize            = FormUtil::getPAssedValue('maxsize', 10000, 'POST');
    $maxheight          = FormUtil::getPAssedValue('maxheight', 80, 'POST');
    $maxwidth           = FormUtil::getPAssedValue('maxwidth', 80, 'POST');
    $allowed_extensions = FormUtil::getPAssedValue('allowed_extensions', 'gif;jpg;png', 'POST');
    $allow_resize       = FormUtil::getPAssedValue('allow_resize', 1, 'POST');
    $prefix_group_1     = FormUtil::getPAssedValue('prefix_group_1', '', 'POST');
    $prefix_group_2     = FormUtil::getPAssedValue('prefix_group_2', '', 'POST');
    $prefix_group_3     = FormUtil::getPAssedValue('prefix_group_3', '', 'POST');
    $prefix_prefix_1    = FormUtil::getPAssedValue('prefix_prefix_1', '', 'POST');
    $prefix_prefix_2    = FormUtil::getPAssedValue('prefix_prefix_2', '', 'POST');
    $prefix_prefix_3    = FormUtil::getPAssedValue('prefix_prefix_3', '', 'POST'); 

    $extensions = explode(';', $allowed_extensions);
    foreach ($extensions as $key=>$extension) {
        $extensions[$key] = str_replace('.', '', trim($extension));
    }
    $allowed_extensions = implode(';', $extensions);

    pnModSetVar('Avatar', 'avatardir',          $avatardir);
    pnModSetVar('Avatar', 'forumdir',           $forumdir);
    pnModSetVar('Avatar', 'allow_resize',       ($allow_resize == 'allow_resize'));
    pnModSetVar('Avatar', 'maxsize',            (int)$maxsize);
    pnModSetVar('Avatar', 'maxheight',          (int)$maxheight);
    pnModSetVar('Avatar', 'maxwidth',           (int)$maxwidth);
    pnModSetVar('Avatar', 'allowed_extensions', $allowed_extensions);
    pnModSetVar('Avatar', 'prefix_group_1',     $prefix_group_1);
    pnModSetVar('Avatar', 'prefix_group_2',     $prefix_group_2);
    pnModSetVar('Avatar', 'prefix_group_3',     $prefix_group_3);
    pnModSetVar('Avatar', 'prefix_prefix_1',    $prefix_prefix_1);
    pnModSetVar('Avatar', 'prefix_prefix_2',    $prefix_prefix_2);
    pnModSetVar('Avatar', 'prefix_prefix_3',    $prefix_prefix_3);

    return pnRedirect(pnModURL('Avatar', 'admin', 'main'));
}
?>